import { CYRILLIC, uaOnlyLetters } from './letters.mjs';
import { cachedBlob } from './plan.mjs';
import { categoryFile, parseCategory, readCategoryTarget } from './categories.mjs';
import { abs, readIfExists } from './pages.mjs';

// `write-translations` fills a locale's docs-plugin `current.json` with the sidebar's category labels in the default
// language. Docusaurus prefers that file over the title of the category's section page, so an autogenerated sidebar then
// shows UA labels in every locale. Category entries that no tracked `_category_.json` owns and that are still Ukrainian
// are such leftovers. Tracked categories are not looked at: `status` already counts them as stale until translated.
const LABEL_KEY = /^sidebar\..+\.category\./;
const GENERATED_INDEX = /\.link\.generated-index\.(title|description)$/;

export async function sidebarOverrides(s, targets, categories) {
  const parsed = [];
  for (const c of categories) {
    const p = parseCategory(await cachedBlob(s.root, c.blob));
    if (!p.error) parsed.push(p);
  }
  const byLocale = new Map();
  for (const locale of targets) {
    const file = categoryFile(s, locale);
    const raw = await readIfExists(abs(s, file));
    let data = null;
    try {
      data = raw === null ? null : JSON.parse(raw);
    } catch {
      /* an invalid file is reported by the tracked categories' cells */
    }
    if (!data || typeof data !== 'object') continue;
    const owned = new Set();
    for (const p of parsed) for (const e of (await readCategoryTarget(s, locale, p)).entries) owned.add(e.entryKey);
    const labels = Object.entries(data)
      .filter(([key, v]) => LABEL_KEY.test(key) && !GENERATED_INDEX.test(key) && !owned.has(key) && typeof v?.message === 'string')
      .map(([entryKey, v]) => ({ entryKey, message: v.message }));
    byLocale.set(locale, { file, labels });
  }
  // The same Cyrillic message in two or more locales is the default-language text copied, not a translation.
  const copies = new Map();
  for (const { labels } of byLocale.values()) for (const l of labels) if (CYRILLIC.test(l.message)) copies.set(`${l.entryKey}\0${l.message}`, (copies.get(`${l.entryKey}\0${l.message}`) ?? 0) + 1);
  const out = [];
  for (const [locale, { file, labels }] of byLocale) {
    const untranslated = labels.filter((l) => uaOnlyLetters(l.message, locale) || (CYRILLIC.test(l.message) && copies.get(`${l.entryKey}\0${l.message}`) > 1));
    if (untranslated.length) out.push({ locale, file, entries: untranslated });
  }
  return out;
}

export function sidebarWarning({ locale, file, entries }) {
  const shown = entries.slice(0, 3).map((e) => `«${e.message}»`).join(', ');
  return (
    `${file} holds ${entries.length} sidebar category label${entries.length === 1 ? '' : 's'} still in Ukrainian (${shown}${entries.length > 3 ? ', …' : ''}). ` +
    `Docusaurus shows them in the ${locale} sidebar instead of the translated titles of the section pages. ` +
    `Where the sidebar is autogenerated and the UA tree has no _category_.json for these folders, delete the file (write-translations recreates it with the UA text: do not rerun it for this locale). ` +
    `To translate the labels instead, add a _category_.json for each folder in the UA tree.`
  );
}
